"""MUSA command line.

  python -m musa_sentinel scan "Pay today, 100% visa guarantee"     # scan a recruiter message
  python -m musa_sentinel scan --file chat.txt
  python -m musa_sentinel firewall samples/payment_request.json      # PAY / HOLD / ESCALATE
  python -m musa_sentinel graph samples/entities.json                # identity-reuse detection
  python -m musa_sentinel leads                                      # prioritised outreach queue
  python -m musa_sentinel match samples/candidate.json samples/jobs.json
  python -m musa_sentinel forecast --scenario base --months 12
  python -m musa_sentinel draft partner_oep contact=Ali company=MUSA sender=Musa phone=+92... price=99
  python -m musa_sentinel build                                      # regenerate public/musa/traps.js + Dashy page
"""
import argparse
import json
import os
import sys

from . import DATA_DIR, PACKAGE_DIR
from . import firewall, graph as graph_mod, leads, matching, outreach, revenue, risk, traps

ROOT = os.path.dirname(PACKAGE_DIR)
_COLOUR = {"GREEN": "\033[32m", "AMBER": "\033[33m", "RED": "\033[31m", "BLACK": "\033[35m"}


def _load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _out(obj, as_json):
    print(json.dumps(obj, indent=2, ensure_ascii=False, default=list) if as_json else obj)


def cmd_scan(a):
    text = open(a.file, encoding="utf-8").read() if a.file else " ".join(a.text)
    res = traps.assess_message(text)
    if a.json:
        return _out(res, True)
    d = res["decision"]
    tty = sys.stdout.isatty()
    print("%s%s → %s%s   risk %d (%s)" % (_COLOUR.get(d["colour"], "") if tty else "", d["colour"], d["action"],
                                         "\033[0m" if tty else "", d["risk"]["score"], d["risk"]["band"]))
    for h in res["hits"]:
        print("\n[%s] %s — %s\n  evidence: …%s…\n  reply:    %s\n  urdu:     %s" % (
            h["severity"].upper(), h["id"], h["name"], h["evidence"], h["response"], h["response_ur"]))
    if not res["hits"]:
        print("No known trap patterns. That does NOT mean the offer is genuine — nothing has been verified yet.")


def cmd_firewall(a):
    req = _load(a.request)
    g = None
    if a.graph:
        g = graph_mod.ReputationGraph()
        for e in _load(a.graph)["entities"]:
            g.add_entity(e["id"], e["name"], e.get("type", "recruiter"), e.get("identifiers"), e.get("outcomes"))
    res = firewall.evaluate(req, graph=g, case_evidence=req.get("case_evidence"))
    if a.json:
        return _out(res, True)
    print("PAYMENT %s  €%s  →  %s  (human approval required)" % (res["payment_id"], res["amount"], res["decision"]))
    for r in res["reasons"]:
        print("  • " + r)
    print("\nFee ledger:")
    for k, v in res["fee_ledger"].items():
        if k != "by_category":
            print("  %-24s %s" % (k, v))


def cmd_graph(a):
    data = _load(a.entities)
    g = graph_mod.ReputationGraph()
    for e in data.get("entities", []):
        g.add_entity(e["id"], e["name"], e.get("type", "recruiter"), e.get("identifiers"), e.get("outcomes"))
    res = {"identity_reuse": g.find_reuse(), "template_reuse": graph_mod.template_reuse(data.get("documents", {}))}
    _out(res, True)


def cmd_leads(a):
    q = leads.outreach_queue(include_authorities=a.all)
    if a.json:
        return _out(q, True)
    for i, l in enumerate(q, 1):
        contact = ", ".join("%s: %s" % kv for kv in l["methods"].items())
        print("%2d. [%2d/10] %-40s tier %s  %s\n     %s\n     → %s" % (i, l["score"], l["name"], l["source_tier"], l["status"].upper(), contact, l["next_step"]))


def cmd_match(a):
    _out(matching.rank(_load(a.candidate), _load(a.jobs)), True)


def cmd_forecast(a):
    fc = revenue.forecast(a.months, a.scenario)
    _out(fc, True) if a.json else print(revenue.format_table(fc))


def cmd_draft(a):
    if not a.template:
        for name in outreach.TEMPLATES:
            print("%-22s needs: %s" % (name, ", ".join(outreach.fields(name))))
        return
    values = dict(kv.split("=", 1) for kv in a.vars)
    print(outreach.render(a.template, **values))


def build_web(path=None):
    data = _load(os.path.join(DATA_DIR, "traps.json"))
    path = path or os.path.join(os.path.dirname(ROOT), "public", "musa", "traps.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// GENERATED by `python -m musa_sentinel build` from data/traps.json — do not edit by hand.\n")
        f.write("window.MUSA_TRAPS = %s;\n" % json.dumps(data["traps"], ensure_ascii=False, indent=1))
        f.write("window.MUSA_RISK = %s;\n" % json.dumps({"weights": risk.RISK_WEIGHTS, "hard_stops": risk.HARD_STOPS, "bands": risk.BANDS}, ensure_ascii=False))
    return path


def _yaml_str(s):
    return json.dumps(str(s), ensure_ascii=False)


def build_dashy(path=None):
    """Render the MUSA command-centre as a Dashy sub-page from the lead register + pricing."""
    contacts = leads.load_contacts()
    pricing = revenue.load_pricing()
    fc = revenue.forecast(12, "base")
    queue = {l["name"]: l for l in leads.outreach_queue(contacts, include_authorities=True)}

    def link(c):
        m = c.get("methods", {})
        if m.get("website"):
            return m["website"]
        if m.get("email"):
            return "mailto:" + m["email"]
        if m.get("whatsapp") or m.get("phone"):
            return "https://wa.me/" + "".join(ch for ch in (m.get("whatsapp") or m["phone"]) if ch.isdigit())
        if m.get("telegram"):
            return "https://t.me/" + m["telegram"].lstrip("@")
        return ""

    def item(title, desc, url, icon, extra=""):
        out = "  - title: %s\n    description: %s\n    icon: %s\n" % (_yaml_str(title), _yaml_str(desc), icon)
        if url:
            out += "    url: %s\n    target: newtab\n" % _yaml_str(url)
        return out + extra

    groups = [
        ("Tier 0 · Official Sources", "fas fa-landmark", [c for c in contacts if c["role"] == "authority"], "fas fa-landmark"),
        ("B2B Partners · Cyprus Agencies (UNVERIFIED)", "fas fa-handshake", [c for c in contacts if c["role"] == "b2b_partner"], "fas fa-building"),
        ("Legal Referral Partners", "fas fa-balance-scale", [c for c in contacts if c["role"] == "legal"], "fas fa-gavel"),
        ("Job & Demand Channels", "fas fa-briefcase", [c for c in contacts if c["role"] == "channel"], "fas fa-search-dollar"),
    ]
    y = ["---", "# GENERATED by `python -m musa_sentinel build` — edit musa/data/*.json instead.",
         "pageInfo:", "  title: MUSA Command Centre",
         "  description: Pakistan → Cyprus corridor · verify first, then earn",
         "sections:"]
    y.append("- name: Revenue Engine (12-mo base forecast)\n  icon: fas fa-coins\n  displayData:\n    cols: 2\n  items:")
    y.append(item("Forecast: €%s revenue / ending MRR €%s" % (format(fc["total_revenue"], ","), fc["ending_mrr"]),
                  "First profitable month: %s · run `python -m musa_sentinel forecast`" % fc["first_profitable_month"], "", "fas fa-chart-line").rstrip())
    for p in pricing["products"]:
        unit = "/mo" if p["type"] == "monthly" else ""
        y.append(item("%s — €%s%s" % (p["name"], p["price"], unit), "%s · %s" % (p["buyer"], p["purpose"]), "", "fas fa-tag").rstrip())
    y.append("- name: Scam Shield & Tools\n  icon: fas fa-shield-alt\n  items:")
    y.append(item("Scam Shield (public lead magnet)", "Workers paste a recruiter message → risk band → WhatsApp CTA", "/musa/index.html", "fas fa-user-shield").rstrip())
    y.append(item("BEOE Foreign Jobs — Cyprus", "Search live permissions; open each permission before trusting it", "https://beoe.gov.pk/foreign-jobs", "fas fa-search").rstrip())
    for title, icon, items, item_icon in groups:
        y.append("- name: %s\n  icon: %s\n  items:" % (_yaml_str(title), icon))
        for c in sorted(items, key=lambda c: -queue[c["name"]]["score"]):
            desc = "[score %d · tier %s · %s] %s" % (queue[c["name"]]["score"], c.get("source_tier"), c.get("status", "").upper(), c.get("specialization", ""))
            y.append(item(c["name"], desc, link(c), item_icon).rstrip())
    out = "\n".join(y) + "\n"
    path = path or os.path.join(os.path.dirname(ROOT), "user-data", "musa.yml")
    with open(path, "w", encoding="utf-8") as f:
        f.write(out)
    return path


def cmd_build(a):
    print("wrote", build_web())
    print("wrote", build_dashy())


def main(argv=None):
    p = argparse.ArgumentParser(prog="musa_sentinel", description="MUSA Visa Sentinel — verify before anyone pays.")
    p.add_argument("--json", action="store_true", help="machine-readable output")
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("scan", help="scan a recruiter message for trap patterns")
    s.add_argument("text", nargs="*")
    s.add_argument("--file")
    s.set_defaults(fn=cmd_scan)

    s = sub.add_parser("firewall", help="evaluate a payment request")
    s.add_argument("request")
    s.add_argument("--graph", help="entities.json for reputation lookups")
    s.set_defaults(fn=cmd_firewall)

    s = sub.add_parser("graph", help="identity & document-template reuse")
    s.add_argument("entities")
    s.set_defaults(fn=cmd_graph)

    s = sub.add_parser("leads", help="prioritised outreach queue")
    s.add_argument("--all", action="store_true", help="include official sources")
    s.set_defaults(fn=cmd_leads)

    s = sub.add_parser("match", help="rank jobs for a candidate")
    s.add_argument("candidate")
    s.add_argument("jobs")
    s.set_defaults(fn=cmd_match)

    s = sub.add_parser("forecast", help="revenue forecast")
    s.add_argument("--months", type=int, default=12)
    s.add_argument("--scenario", choices=sorted(revenue.SCENARIOS), default="base")
    s.set_defaults(fn=cmd_forecast)

    s = sub.add_parser("draft", help="render an outreach template (no args: list templates)")
    s.add_argument("template", nargs="?")
    s.add_argument("vars", nargs="*", help="key=value")
    s.set_defaults(fn=cmd_draft)

    s = sub.add_parser("build", help="regenerate public/musa/traps.js and the Dashy page")
    s.set_defaults(fn=cmd_build)

    a = p.parse_args(argv)
    a.fn(a)


if __name__ == "__main__":
    main()
